#HTTP port config
server:
  port: 8088

# Spring cloud configurations
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        service-name: cliente-api
        tags: cliente,cliente-api
